name: SonarQube Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SonarQube Scanner
        run: sonar-scanner
        env:
          SONAR_TOKEN: sqp_c1c638b93f8ea39847655e813ab67f3af1ae4a9c
