name: SonarQube Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download and extract SonarScanner
        run: |
          sudo apt-get install -y openjdk-11-jre
          export SONAR_SCANNER_VERSION=4.6.2.2472
          curl -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip
          unzip sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip -d $HOME
          SONAR_SCANNER_PATH="${PWD}/sonar-scanner-${SONAR_SCANNER_VERSION}-linux/bin"

      - name: Run SonarQube Scanner
        run: $SONAR_SCANNER_PATH/sonar-scanner
        env:
          SONAR_TOKEN: sqp_c1c638b93f8ea39847655e813ab67f3af1ae4a9c
